version: '3.3'
services:
  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0D2B87E1DE55A9BD89009B37979CACD984AA773C7197BE3F46DCB15B0CAE7E6D
      MYSQL_DATABASE: glasses
      MYSQL_USER: springUser
      MYSQL_PASSWORD: springUser
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - docker-mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: docker-mysql
  spring:
    container_name: springapp
    image: verkeur08/gestionglasses:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql/glasses?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springUser
      SPRING_DATASOURCE_PASSWORD: springUser
    depends_on:
      - docker-mysql
